### ISSUE TITLE
Crash nach Spielende

### ISSUE THREAD

**Issue by Timmifixedit** [SoPra-Team-10/Server#106]
Asan killt den Server wegen SEGV nach einer vollständigen Partie (Schnatz wurde in der Überlänge von einem Sucher gefangen). Anscheinend wird ein illegaler Read-Zugriff ausgeführt ("Address points to zero page"). Beim Client kommt aber auf jeden Fall noch der letzte Snapshot an. Könnte auf ein Problem beim Destruieren des Games hinweisen...

**Comment by Timmifixedit** [comment]
In der Meldung stand aber auch was von LWS. Ich versuche den Fehler nochmal zu provozieren...

**Comment by Timmifixedit** [comment]
AddressSanitizer:DEADLYSIGNAL
=================================================================
==32412==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c2 (pc 0x7ff50c337246 bp 0x61200007f850 sp 0x7ff508efed00 T1)
==32412==The signal is caused by a READ memory access.
==32412==Hint: address points to the zero page.
    #0 0x7ff50c337245 in rops_write_role_protocol_ws (/usr/local/lib/libwebsockets.so.14+0x1e245)
    #1 0x7ff50c329b65 in lws_write (/usr/local/lib/libwebsockets.so.14+0x10b65)
    #2 0x7ff50d6aa0e9 in network::WebSocketServer::sendImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, lws*) (/usr/local/lib/libSopraNetwork.so.1+0x50e9)
    #3 0x7ff50d6acf40 in std::_Function_handler<void (), std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, lws*))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, lws*)> >::_M_invoke(std::_Any_data const&) (/usr/local/lib/libSopraNetwork.so.1+0x7f40)
    #4 0x7ff50d6a9e11 in network::WebSocketServer::run() (/usr/local/lib/libSopraNetwork.so.1+0x4e11)
    #5 0x7ff50d3d966e  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd66e)
    #6 0x7ff50dfde6da in start_thread /build/glibc-OTsEL5/glibc-2.27/nptl/pthread_create.c:463
    #7 0x7ff50ce3488e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12188e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/lib/libwebsockets.so.14+0x1e245) in rops_write_role_protocol_ws
Thread T1 created by T0 here:
    #0 0x7ff50e2479ef in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x519ef)
    #1 0x7ff50d3d9924 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd924)
    #2 0x7ffd1a8587b7  ([stack]+0x1f7b7)

==32412==ABORTING

**Comment by aul12** [comment]
@Timmifixedit bei dir ist das auch nicht mehr aufgetreten, oder?
