### ISSUE TITLE
Schnittstelle zwischen Kommunikation und GameLogic

### ISSUE THREAD

**Issue by aul12** [SoPra-Team-10/Server#9]
Welches Modul kümmert sich um:
 - [x] Pause: GameController
 - [x] Timeouts: GameController
 - [x] Nächsten Zug verlangen: GameController
 - [x] Verifizieren ob gesendeter Zug korrekt: GameController
 - [x] Gewinn bestimmen
 - [x] TeamFormation verarbeiten und Spiel starten: GameController
 - [x] MatchConfig verarbeiten (und evtl. einlesen), muss aber auch in der Lobby bekannt sein: Config in Controller
 - [x] TeamConfig verarbeiten, muss in der Lobby auch bekannt sein: Gamecontroller

**Comment by jonas-merkle** [comment]
Das ist eine gute Frage würde es sich nicht anbieten da ein extra Modul zu machen und des dann den ganzen Spielablauf managed?
